### ISSUE TITLE
Intern : Ramp-up : BE : Adarsh Pal

### ISSUE THREAD

**Issue by ArunJainProcursorsMain** [karthik-vishwakarma/zanwix-ramp-up#3]
# Machine Setup

## Install brew 

1. Commands to install brew 
 `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
2.  After that you can see this command in terminal simply copy the complete command from your machine to setup the path  and run on terminal below is the given example ->

![Image](https://github.com/user-attachments/assets/7c702500-0ec8-44d6-8b3e-2fb3e0473307)

 ```
(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/arunjain/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
```

## Install Java 17
 To install jdk 7 use the run the following command in terminal 
 `brew install openjdk@17`
 
## Install Maven  
Run the following command in terminal
`brew install mvn`

##  Setup Intelliaj community edition 
1. Copy and paste the below url on chrome browser to donwload
`https://www.jetbrains.com/idea/download/download-thanks.html?platform=macM1&code=IIC`
2. Install the Intelliaj and added the maven path in maven settings.
  Follow the steps - >
 (i) Run command in terminal 
   ` mvn -version`
(ii) Copy the maven home path ex - `/opt/homebrew/Cellar/maven/3.9.8/libexec`
(iii) Set it on maven setting below is the screenshot.
![Image](https://github.com/user-attachments/assets/15c38886-2da0-4c74-a367-2c65347d8d40)

3. Install the below plugins 
  (i)Docker
  (ii)GitToolBox
  (iii)Lombok
  (iv)Markdown Editor
  (v)Rainbow Brackets
  (vi)One Dark Theme (Optional)
  (vii)Sonar Lint
  (viii)String Manipulation
  
## Setup Visual Studio Community Edition
 `https://visualstudio.microsoft.com/downloads/`

## Install Mysql / or any compatible software for the Database 
Visit this link to download the mysql 
`https://dev.mysql.com/get/Downloads/MySQL-9.0/mysql-9.0.0-macos14-arm64.dmg` 
To download workbench 
`https://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community-8.0.38-macos-x86_64.dmg` 

## Install git
1. Run the following command in terminal
`brew install git`

2. Generate and setup the rsa key
(i) Run the following command in terminal
`ssh-keygen -b 4096 -t rsa`
(ii) Open the id_rsa.pub file following the path shows in terminal
(iii) Copy the entire key.
(iv) Go to Github setting -> click on ssh and gpg option -> paste inside the  add new key in ssh.
(v) Use the same public key while clone the first repository access as authentication.

![Image](https://github.com/user-attachments/assets/cdb970cf-4b11-4626-88c3-10f69a5bf890)

## Install Postman
Run the following command in terminal 
`brew install postman`

## Install Docker
Copy and paste the below url on chrome browser 
`https://desktop.docker.com/mac/main/arm64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-mac-arm64&_gl=1*jou58z*_ga*MTQ0MDM0MDI1OC4xNzIxNDUwMTE5*_ga_XJWPQMJYHQ*MTcyMTQ1MDExOS4xLjEuMTcyMTQ1MDEyMC41OS4wLjA.`

## Install npm
 `brew install node`

# Repository & Architecture Overview.
   It is given by Karthik Vishwakarma

# Implement User Management.
Create a demo project which perform the crud operation related to user management.

**Comment by adpal2003** [comment]
I have successfully completed the following setup:
Installed Java 17.
Installed Maven.
Set up IntelliJ IDEA Community Edition and configured Maven.
Installed the required plugins in IntelliJ IDEA.
Set up Visual Studio Community Edition.
Installed MySQL and MySQL Workbench.
Installed Git and set up RSA keys for GitHub authentication.
Installed Postman.
Installed Docker.
Installed npm.
Ready to proceed with the implementation of user management.

**Comment by karthik-vishwakarma** [comment]
Custom exception handler review is pending.
